/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Entidades.Cliente;
import Entidades.Cuenta;
import Entidades.Transferencia;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import persistencia.ClientesDAO;
import persistencia.ConexionBD;
import persistencia.CuentasDAO;
import persistencia.IClientesDAO;
import persistencia.ICuentasDAO;
import persistencia.ITransferenciaDAO;

/**
 *
 * @author diego
 */
public class frmTranferir extends javax.swing.JFrame {
    IClientesDAO clienteDAO;
  Cliente cliente;
    ICuentasDAO CuentasDAO;
    ITransferenciaDAO Transferencia;
    private float sueldoresta,sueldosuma;
      private Cuenta cuenta,cuentaenvio;
    /**
     * Creates new form frmTranferir
     */
    public frmTranferir(ITransferenciaDAO TransferenciaDAO,Cuenta cuenta,Cliente cliente,ICuentasDAO cuentasDAO) {
     this.CuentasDAO=cuentasDAO;
     this.cliente=cliente;
        this.clienteDAO=clienteDAO;
        this.Transferencia=TransferenciaDAO;
        this.cuenta=cuenta;
        initComponents();
   
       lblNumeroCliente.setText("Numero de Cliente: "+cliente.getIdCliente());
         lblNumeroCuenta2.setText("Numero de Cuenta: "+cuenta.getNumeroCuenta());
    }
    
   public boolean operacion(){
       
       if(cuenta.getSaldo()>Float.valueOf(txtCantidad.getText())){
        if(CuentasDAO.buscarPorNumeroCuenta(txtNumeroCuentaEnvio.getText())!=null) {
           
       
            sueldoresta=cuenta.getSaldo()-Float.valueOf(txtCantidad.getText());
            cuentaenvio=CuentasDAO.buscarPorNumeroCuenta(txtNumeroCuentaEnvio.getText());
             sueldosuma= cuentaenvio.getSaldo()+Float.valueOf(txtCantidad.getText());
           Transferencia trans=new Transferencia();
           trans.setCantidad(txtCantidad.getText());
           trans.setNumeroCuenta(cuenta.getNumeroCuenta());
           trans.setNumeroCuentaEnvio(txtNumeroCuentaEnvio.getText());
          Transferencia.Operacion(sueldoresta, sueldosuma, trans, txtNumeroCuentaEnvio.getText(),cuenta.getNumeroCuenta());
            Transferencia transGuardar = Transferencia.guardar(trans);
                JOptionPane.showMessageDialog(this, "La operación se realizo con exito",
                    "Información", JOptionPane.INFORMATION_MESSAGE);  
        }else{
               JOptionPane.showMessageDialog(this, "No se encontro la cuenta a enviar",
                    "Información", JOptionPane.ERROR_MESSAGE);  
        }
       }else{
              JOptionPane.showMessageDialog(this, "No cuenta con el Saldo suficiente para completar esta operación",
                    "Información", JOptionPane.ERROR_MESSAGE); 
       }
        return false;
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroCuenta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNumeroCuentaEnvio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblNumeroCliente = new javax.swing.JLabel();
        lblNumeroCuenta2 = new javax.swing.JLabel();

        lblNumeroCuenta.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblNumeroCuenta.setText("Numero de Cuenta");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Transferencia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, 30));

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 100, 30));

        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 150, 30));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        getContentPane().add(txtNumeroCuentaEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 142, 100, 30));

        jLabel4.setText("Numero De Cuenta A Enviar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, 20));

        lblNumeroCliente.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblNumeroCliente.setText("Numero de Cliente:");
        getContentPane().add(lblNumeroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblNumeroCuenta2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblNumeroCuenta2.setText("Numero de Cuenta:");
        getContentPane().add(lblNumeroCuenta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
 if (!txtCantidad.getText().equals("")) {
        operacion();
 }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         int opcion = JOptionPane.showConfirmDialog(this, "¿Quieres Volver Al Menu?", "Confirmacion", JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
        if (opcion!=0) {
            
        }else{
            frmInicio inicio = new frmInicio(clienteDAO);
            inicio.setVisible(true);
            this.dispose();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
          int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();

        }

      // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyTyped

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblNumeroCliente;
    private javax.swing.JLabel lblNumeroCuenta;
    private javax.swing.JLabel lblNumeroCuenta2;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNumeroCuentaEnvio;
    // End of variables declaration//GEN-END:variables
}
