/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Entidades.Cliente;
import Entidades.Cuenta;
import Entidades.Transferencia;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import persistencia.ClientesDAO;
import persistencia.ConexionBD;
import persistencia.CuentasDAO;
import persistencia.IClientesDAO;
import persistencia.ICuentasDAO;
import persistencia.ITransferenciaDAO;

/**
 *
 * @author diego
 */
public class frmTranferir extends javax.swing.JFrame {
      private IClientesDAO clienteDAO;
      private Cliente cliente;
      private  ICuentasDAO CuentasDAO;
      private ITransferenciaDAO Transferencia;
      private float sueldoresta,sueldosuma;
      private Cuenta cuenta,cuentaenvio;
      FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form frmTranferir
     */
    public frmTranferir(ITransferenciaDAO TransferenciaDAO,Cuenta cuenta,Cliente cliente,ICuentasDAO cuentasDAO) {
     this.CuentasDAO=cuentasDAO;
     this.cliente=cliente;
        clienteDAO = new ClientesDAO();
        this.Transferencia=TransferenciaDAO;
        this.cuenta=cuenta;
        this.setContentPane(fondo);
        initComponents();
   
         lblNumeroCliente.setText("Nombre del Cliente: "+cliente.getNombres()+" "+cliente.getApellidoPaterno()+" "+cliente.getApellidoMaterno());
         lblNumeroCuenta.setText("Numero de Cuenta: "+cuenta.getNumeroCuenta());
         crearFont();
    }
    
   public boolean operacion(){
       
       if(cuenta.getSaldo()>Float.valueOf(txtCantidad.getText())){
        if(CuentasDAO.buscarPorNumeroCuenta(txtNumeroCuentaEnvio.getText())!=null) {
           
       
            sueldoresta=cuenta.getSaldo()-Float.valueOf(txtCantidad.getText());
            cuentaenvio=CuentasDAO.buscarPorNumeroCuenta(txtNumeroCuentaEnvio.getText());
             sueldosuma= cuentaenvio.getSaldo()+Float.valueOf(txtCantidad.getText());
           Transferencia trans=new Transferencia();
           trans.setCantidad(txtCantidad.getText());
           trans.setNumeroCuenta(cuenta.getNumeroCuenta());
           trans.setNumeroCuentaEnvio(txtNumeroCuentaEnvio.getText());
          Transferencia.Operacion(sueldoresta, sueldosuma, trans, txtNumeroCuentaEnvio.getText(),cuenta.getNumeroCuenta());
            Transferencia transGuardar = Transferencia.guardar(trans);
                JOptionPane.showMessageDialog(this, "La Operación se realizo con exito",
                    "Información", JOptionPane.INFORMATION_MESSAGE); 
                frmMenu menu = new frmMenu(CuentasDAO,clienteDAO,cliente);
               menu.setVisible(true);
               this.dispose();
                
        }else{
               JOptionPane.showMessageDialog(this, "No se encontro la cuenta a enviar",
                    "Información", JOptionPane.ERROR_MESSAGE);  
        }
       }else{
              JOptionPane.showMessageDialog(this, "No Cuenta con el Saldo suficiente para completar esta operación",
                    "Información", JOptionPane.ERROR_MESSAGE); 
       }
        return false;
   }
public void crearFont(){
        //Colocar Colores A Label
        lblTitulo.setForeground(Color.black);
        lblNumeroCuenta.setForeground(Color.black);
        lblNumeroCuentaEnvio.setForeground(Color.black);
        lblNumeroCliente.setForeground(Color.black);
        lblCantidad.setForeground(Color.black);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNumeroCuentaEnvio = new javax.swing.JTextField();
        lblNumeroCuentaEnvio = new javax.swing.JLabel();
        lblNumeroCliente = new javax.swing.JLabel();
        lblNumeroCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        lblTitulo.setText("Transferencia");

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        lblCantidad.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        lblCantidad.setText("Cantidad");

        btnAceptar.setBackground(new java.awt.Color(149, 175, 255));
        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(149, 175, 255));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblNumeroCuentaEnvio.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        lblNumeroCuentaEnvio.setText("Numero De Cuenta A Enviar");

        lblNumeroCliente.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        lblNumeroCliente.setText("Nombre Cliente:");

        lblNumeroCuenta.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        lblNumeroCuenta.setText("Numero de Cuenta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroCuentaEnvio)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(txtNumeroCuentaEnvio))
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroCuenta)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblNumeroCliente)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroCuenta)
                .addGap(22, 22, 22)
                .addComponent(lblNumeroCliente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroCuentaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroCuentaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
 if (txtCantidad.getText().equals("")||txtNumeroCuentaEnvio.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Hay espacios Vacios",
                    "Información", JOptionPane.ERROR_MESSAGE);
 }else{
     operacion();
      
 }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         int opcion = JOptionPane.showConfirmDialog(this, "¿Quieres Volver Al Menu?", "Confirmacion", JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
        if (opcion!=0) {
            
        }else{
            frmMenu menu = new frmMenu(CuentasDAO,clienteDAO,cliente);
            menu.setVisible(true);
            this.dispose();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
          int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();

        }

      // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyTyped

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblNumeroCliente;
    private javax.swing.JLabel lblNumeroCuenta;
    private javax.swing.JLabel lblNumeroCuentaEnvio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNumeroCuentaEnvio;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            ImageIcon imageIcon = new javax.swing.ImageIcon(getClass().getResource("/xp.jpg"));
            imagen = imageIcon.getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);
            try{
                super.paint(g); 
            }catch(Exception e){
                
            }
           
        }
    }
}
